name: workout_tracking_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.2
  cloud_firestore: ^4.9.3
  firebase_core: ^2.24.2
  intl: ^0.18.1
  pagination_view: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  http: ^1.1.0
  firebase_auth: ^4.11.1
  flutter_signin_button: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true